pragma Singleton
import QtQuick

// Colors come from GeneratedColors (wallust-derived from the current
// wallpaper, regenerated by set-wallpaper.sh) instead of a fixed palette —
// that's what makes the whole DE (bar, panels, fuzzel) recolor itself
// automatically on wallpaper change instead of needing a manual retheme.
QtObject {
    // ── Driven by Perception ──
    //
    // Written from outside, not read from Perception, so this file keeps
    // depending on nothing: Context reaches Notifs and Notifs reads Theme, so a
    // Theme that reached for Perception would close that ring while the
    // singletons are still being built. The defaults below are the shell with
    // no interpretation applied, which is also what it looks like if Perception
    // is never constructed.
    //
    // These are the whole of the "living surface": nothing moves a widget, the
    // ladders move, and the several hundred bindings already standing on them
    // carry the change outward. Deliberately not on this list are barHeight and
    // barMargin -- they set the layer-shell exclusive zone, and breathing that
    // would shove every real window on the output back and forth.
    //
    // One semantic owner each, and the ownership is the architecture rather
    // than a convention: if two axes ever wanted the same scalar, they would be
    // one axis. Written down because the next person to add a token will be
    // tempted to reach for whichever one is already in scope.
    //
    //   densityScale  <- spatial     motionScale  <- temporal
    //   inkScale      <- optical     frost        <- optical
    //   emphasis      <- hierarchy
    property real motionScale: 1.0
    property real densityScale: 1.0
    property real inkScale: 1.0
    property bool frost: true
    property real emphasis: 1.0

    // Where deciding ends and presenting begins.
    //
    // Perception emits a number and stops; making that number physical is this
    // file's job. Putting these Behaviors upstream would have made the semantic
    // layer read its own last output to interpolate from it, which is the one
    // thing it is not allowed to do -- and the split is what keeps "what should
    // be true" separable from "how it becomes visible".
    //
    // Long, because none of this is the shell answering an input. Nobody
    // pressed anything, so it must not be timed like a response, and it cannot
    // be timed by the very motion scale it is setting.
    Behavior on motionScale { NumberAnimation { duration: 1400; easing.type: Easing.Bezier; easing.bezierCurve: easeEmphasized } }
    Behavior on densityScale { NumberAnimation { duration: 1400; easing.type: Easing.Bezier; easing.bezierCurve: easeEmphasized } }
    Behavior on inkScale { NumberAnimation { duration: 1400; easing.type: Easing.Bezier; easing.bezierCurve: easeEmphasized } }
    Behavior on emphasis { NumberAnimation { duration: 1400; easing.type: Easing.Bezier; easing.bezierCurve: easeEmphasized } }

    // Hierarchy's own token, and the reason it needed one. The obvious way to
    // pull decorative chrome back was to lower its ink -- but ink belongs to
    // optical, and a second axis writing it would have been two owners for one
    // token. Emphasis therefore gets a scalar of its own rather than borrowing
    // one, which is the ownership rule catching a real mistake rather than
    // describing a hypothetical.
    // Inverted: emphasis rising means the focal thing gets more of the eye, so
    // the decorative chrome gets less. Bottoms out well short of zero -- chrome
    // that disappears entirely reads as the shell having broken, not as the
    // shell being tactful.
    readonly property real chromeEmphasis: Math.max(0.55, Math.min(1.0, 1.70 - emphasis))

    readonly property color crust: Qt.darker(GeneratedColors.background, 1.15)
    readonly property color mantle: GeneratedColors.background
    readonly property color base: Qt.lighter(GeneratedColors.background, 1.12)

    // Ink carries the mood's contrast. Qt.alpha sets alpha absolutely rather
    // than multiplying it, so the derived fills below -- Qt.alpha(text, 0.06)
    // and its neighbours -- are untouched by this and keep their own ladder.
    // Only type drawn in `text` itself pulls back.
    readonly property color text: Qt.alpha(GeneratedColors.foreground, inkScale)
    readonly property color subtext1: Qt.alpha(GeneratedColors.subtext1, inkScale)
    readonly property color subtext0: Qt.alpha(GeneratedColors.subtext0, inkScale)

    readonly property color surface0: GeneratedColors.surface0
    readonly property color surface1: GeneratedColors.surface1
    readonly property color surface2: GeneratedColors.surface2

    readonly property color mauve: GeneratedColors.accent
    readonly property color blue: GeneratedColors.blue
    readonly property color red: GeneratedColors.red
    readonly property color green: GeneratedColors.green
    readonly property color yellow: GeneratedColors.yellow

    readonly property color accent: mauve

    // ── Drawing straight onto the wallpaper ──
    // Panels sit on their own frosted glass and can use `text` safely. The
    // desktop widgets have nothing behind them but the picture, and the accent
    // is derived from that same picture -- so on a bright wallpaper they were
    // being drawn light on light and all but disappeared.
    // Only for a still picture. A video's brightness is measured from one
    // extracted frame, which said 0.31 while the frame actually on screen was
    // 0.82 -- so for video the light treatment is not claimed and the halo
    // below does the work instead.
    readonly property bool wallpaperIsLight:
        !Wallpaper.isVideo && GeneratedColors.meanL > 0.55

    // What to draw on the bare desktop with, in two coherent modes.
    //
    // Light ink with a scrim under it is the default and the only thing that
    // works for video, whose brightness the estimate cannot know. Dark ink with
    // no scrim is used when a still picture is measurably bright, where dark on
    // light is better than either.
    //
    // The dark values are absolute rather than derived: darkening a background
    // that is already near-white gives light grey, which was the first attempt
    // and was unreadable on the white it was meant to fix.
    readonly property color deskInk: wallpaperIsLight
        ? Qt.hsla(0, 0, 0.13, 1)
        : GeneratedColors.foreground
    readonly property color deskAccent: wallpaperIsLight
        ? Qt.hsla(GeneratedColors.accent.hslHue, 0.55, 0.30, 1)
        : GeneratedColors.accent
    // The same alpha does not read the same in the two modes. Measured off the
    // gauge ring: 22% ink gives 1.90:1 against a dark wallpaper and only 1.57:1
    // against a white one, because the ground it sits on is what changed. 30%
    // brings the light mode back to the contrast the dark mode already had --
    // and it is 30 rather than 27 because the dark ink is #212121, not black,
    // so a given alpha lands lighter than the arithmetic on black suggests.
    readonly property real deskInkFaint: wallpaperIsLight ? 0.30 : 0.22

    // Only under light ink. Darkening the ground under dark ink only muddies it.
    readonly property real deskScrim: wallpaperIsLight ? 0 : 0.45

    // ── Type ──
    // One scale, named by role rather than by size, so a label in the bar and a
    // label in the control centre are the same thing by construction instead of
    // by two people picking 10 on separate days. Every size in the shell used to
    // be a literal: 12 and 11 appeared 78 times between them, 9/13/14/15/17/19
    // once or twice each, which is what a scale looks like when there isn't one.
    //
    // Inter is the interface face and Inter Display the optical size cut for
    // anything large — Display's tighter spacing and smaller apertures are what
    // stop a 132px clock reading as a blown-up body font. JetBrains Mono is kept
    // for genuinely tabular material.
    readonly property string fontFamily: "Inter"
    readonly property string fontDisplayFamily: "Inter Display"
    readonly property string fontMonoFamily: "JetBrains Mono"
    // Material Symbols Rounded, variable. Rounded rather than Outlined
    // because Inter is a humanist face with open, rounded terminals, and
    // Outlined's square cuts read as a second designer having a go.
    readonly property string fontIconFamily: "Material Symbols Rounded"

    readonly property int fontMicro: 9
    readonly property int fontLabel: 10
    readonly property int fontSmall: 11
    readonly property int fontBody: 12
    readonly property int fontLead: 13
    readonly property int fontTitle: 15
    // Glyphs used to sit a rung or two *above* the text beside them, because a
    // Nerd Font symbol does not fill its em box and a letter nearly does. That
    // reasoning was correct and it is now obsolete: Material Symbols is drawn
    // on a grid where the glyph *is* the box, so an icon set to the same pixel
    // size as its label already reads a shade larger than it. Keeping the old
    // rungs made every icon in the bar about a fifth too big on the first
    // build, which is what a ladder inherited across a change of material
    // looks like.
    //
    // So the ladder is now roughly the type scale itself, one step up.
    readonly property int fontIconMicro: 12
    readonly property int fontIconSmall: 13
    readonly property int fontIcon: 16
    // Display size, for a glyph that is the subject of its own area rather than
    // a label's companion — the weather card, an empty state.
    readonly property int fontIconHero: 36

    readonly property int fontDisplay: 22
    // Type that is the subject of its own small area — a ring's number, an
    // avatar's initial, the glyph an empty panel is built around. Named because
    // the gap between display and hero was where 26, 30 and 19 were each
    // invented separately for the same job.
    readonly property int fontHeadline: 30
    readonly property int fontHero: 40
    // One rung above hero, and only the desktop clock stands on it. It is the
    // one piece of type in the shell meant to be read across a room rather than
    // across a panel, and leaving it as a literal is how 96 ended up sitting
    // beside a scale that stopped at 40 without either of them knowing.
    readonly property int fontClock: 112

    // Tracking. Small type needs opening up and large type needs closing in;
    // both are what separates set type from defaulted type.
    readonly property real trackLabel: 1.2
    readonly property real trackBody: 0
    readonly property real trackDisplay: -0.6
    // All-caps set small under something large — the desktop date and the lock
    // screen's. Caps have no ascenders or descenders to space them, so at label
    // tracking they clot into a bar; this is the width that reads as a caption
    // deliberately set under a display rather than as a line that ran out of
    // room.
    readonly property real trackCaption: 3.0

    // ── Elevation ──
    // Three levels rather than one shadow reused everywhere: the bar sits on the
    // desktop, panels sit above the bar, and anything modal sits above those.
    // Reading the depth is how the eye knows which surface answers a click.
    // The base values mirror niri's own shadow block in 25-appearance.kdl, so
    // the shell's surfaces and real windows cast the same light.
    readonly property color shadowColor: "#11111b90"
    readonly property real shadowBlur: 40
    readonly property real shadowSpread: 4
    readonly property point shadowOffset: Qt.point(0, 6)

    readonly property real elevBarBlur: 22
    readonly property real elevBarSpread: 1
    readonly property real elevPanelBlur: 40
    readonly property real elevPanelSpread: 4
    readonly property real elevModalBlur: 72
    readonly property real elevModalSpread: 8

    // 10 matches niri's own geometry-corner-radius (40-window-rules.kdl) —
    // every quickshell panel uses the same radius as real windows so the
    // shell doesn't read as a separate layer bolted on top of the DE.
    readonly property int radius: 10
    // Popup panels round much harder than niri's own windows — at window
    // radius they read as plain dialogs rather than part of the shell.
    readonly property int radiusLarge: 24

    // ── The shape ladder ──
    //
    // Four steps, and everything on screen picks one. Counted before this
    // existed: sixteen different radii across the tree, chosen one surface at
    // a time. Nothing was individually wrong and the whole never looked like
    // one object, because a family of shapes is what makes surfaces read as
    // relatives rather than as neighbours.
    //
    // The steps grow with the thing they round: a 20px pip and a 400px sheet
    // cannot share a radius and still look equally rounded.
    readonly property int radiusPip: 4       // marks, bars, ticks
    readonly property int radiusChip: 10     // chips, rows, small controls
    readonly property int radiusCard: 16     // cards inside a panel
    readonly property int radiusPanel: 24    // panels and sheets themselves

    // A pill for anything whose height is its identity -- a chip, a toggle,
    // a badge. Written as a function so the call site cannot drift from the
    // height it is rounding.
    function pill(height) {
        return height / 2;
    }

    // ── The surface ladder ──
    //
    // Every raised thing is the same ink at a different strength, so the
    // difference between resting, hovered and pressed is one step of one
    // scale rather than a number picked per widget. There were twelve
    // distinct alphas before this; twelve is not a scale, it is a habit.
    readonly property real fillSubtle: 0.06   // a card at rest
    readonly property real fillMuted: 0.10    // tracks, wells, hairlines
    readonly property real fillHover: 0.14    // the pointer is on it
    readonly property real fillActive: 0.20   // pressed, or selected
    readonly property real strokeSoft: 0.10   // an edge that only separates
    readonly property real strokeFirm: 0.18   // an edge that also lifts

    // The same ladder in a colour, and it is not the same numbers.
    //
    // A saturated hue at ink strength is invisible: the accent at 0.06 is a
    // rumour, where `text` at 0.06 is a card. Six files had each found this out
    // separately and settled on 0.16, 0.22, 0.24, 0.26 and 0.30 — which is one
    // ladder discovered five times. What has to match between an accent-
    // selected row and an ink-hovered one is the *weight*, never the number.
    readonly property real tintSubtle: 0.16   // selected, or a warning at rest
    readonly property real tintActive: 0.26   // pressed, or a warning that must land

    // ── The veil ladder ──
    //
    // Ink laid *over* content rather than under it. The rungs above stop at
    // 0.20 because a fill is a surface you put things on; a veil is a scrim you
    // put over things, and the two were being drawn from one handful of numbers
    // picked per site — thirty-odd distinct values above the top fill rung, for
    // five jobs. Every three-stop scrim in the shell is three of these.
    readonly property real veilThin: 0.30     // you can still read what is under it
    readonly property real veilSoft: 0.45     // present, no longer the subject
    readonly property real veilFirm: 0.60     // legible as shape, not as detail
    readonly property real veilDense: 0.75    // the ground wins
    readonly property real veilSolid: 0.88    // opaque, still tinted by what is behind

    // ── The ink ladder ──
    //
    // The three named inks say *which* grey. This says how much of it a mark
    // keeps, which is a different question and was being answered with 0.28,
    // 0.34, 0.35, 0.45, 0.5, 0.6, 0.65, 0.75 and 0.8 in adjacent files — a
    // weekend in the calendar and a hint under a tooltip are the same gesture
    // and had no way of knowing it.
    readonly property real inkStrong: 0.80    // a step below its own ink
    readonly property real inkSoft: 0.60      // secondary within secondary
    readonly property real inkFaint: 0.45     // present, not for reading at speed
    readonly property real inkGhost: 0.28     // a mark that is only there to be there

    // ── The spacing ladder ──
    //
    // Multiples of four, because the eye reads rhythm and not arithmetic: a
    // 13 next to a 14 is noise that nobody can name but everybody feels.
    //
    // Scaled by the mood, and rounded: a fractional gap lands type on a half
    // pixel and the whole shell goes soft mid-transition.
    readonly property int gapTight: Math.round(4 * densityScale)
    readonly property int spacing: Math.round(8 * densityScale)
    readonly property int gapWide: Math.round(12 * densityScale)
    readonly property int gapCard: Math.round(16 * densityScale)
    readonly property int gapSection: Math.round(24 * densityScale)
    // Islands need more presence than a hairline strip — at 28 the frosted
    // glass and its glow had no room to read as an actual surface.
    readonly property int barHeight: 34
    readonly property int barMargin: 8

    // Faster than a response: the pop of an icon under a click, the shake of
    // the bell. These are not the shell answering, they are the shell
    // acknowledging, and at 120 an acknowledgement reads as a slow answer.
    readonly property int animFlick: Math.round(90 * motionScale)
    readonly property int animFast: Math.round(120 * motionScale)
    readonly property int animNormal: Math.round(220 * motionScale)
    readonly property int animSlow: Math.round(420 * motionScale)
    // Panels leave faster than they arrive: a slow exit reads as sluggish,
    // and an accelerating curve reaches true 0 before the window unmaps so
    // there's no visible snap at the end (see easeExit).
    readonly property int animExit: Math.round(170 * motionScale)

    // Ambient motion, which is not response motion. The three rungs above say
    // how fast the shell answers; these two say how fast something breathes to
    // show it is alive, and the difference between them carries meaning:
    // `busy` is a thing working and worth waiting for, `breath` is a thing
    // simply running. Three separate widgets had invented 520, 700 and 900 for
    // the same infinite opacity pulse, and only one of them said why.
    readonly property int animBusy: Math.round(520 * motionScale)
    readonly property int animBreath: Math.round(800 * motionScale)

    // Below response. Not the length of a move but the leg of an oscillation —
    // the shake a wrong password gets, and nothing else. At flick length its
    // three legs read as three separate movements instead of as one refusal.
    readonly property int animTick: Math.round(55 * motionScale)

    // ── Transition ──
    //
    // Neither the shell answering nor a thing idling: a picture changing, a
    // lock screen arriving, a sleeve's colour taking hold. Nobody pressed
    // anything and nothing is looping, and both existing groups were the wrong
    // shape — at animSlow a wallpaper change is a cut, at animBreath it is a
    // smear. Twenty-six distinct literals lived in this gap because the gap had
    // no names in it.
    readonly property int animEnter: Math.round(620 * motionScale)
    readonly property int animArrive: Math.round(900 * motionScale)
    // Slow enough that nobody watches it happen, which is the point: a still
    // wallpaper that drifts is not a frozen screen.
    readonly property int animDrift: Math.round(1500 * motionScale)
    // Asleep. One motif — the bongo cat, in four files — and it is the only
    // thing in the shell that should look slower than the room it is in.
    readonly property int animDoze: Math.round(2400 * motionScale)

    // Material-3-style "emphasized" decelerate curve — everything that
    // settles into place (panel open, hover fill, list reveal) uses this
    // instead of a plain cubic so motion reads as designed rather than a
    // stock Qt tween. easeSpring adds a slight overshoot for elements that
    // should feel tactile (focused workspace pill, toast pop-in) — this is
    // the single biggest lever for the "caelestia-grade" cohesive-motion
    // look, since every animated Behavior in the shell pulls from the same
    // two curves instead of each panel inventing its own.
    readonly property var easeEmphasized: [0.05, 0.7, 0.1, 1.0, 1, 1]
    readonly property var easeSpring: [0.34, 1.70, 0.60, 1.0, 1, 1]
    // Harder overshoot for panel entrances — a small scale change reads as
    // barely animated, so opens punch in with this and a wider scale delta.
    // The overshoot is what carries "animated", not the duration: raising the
    // amplitude makes motion read as more deliberate, where raising the
    // duration would only make the shell feel slow to answer.
    readonly property var easeSpringBig: [0.22, 2.15, 0.45, 1.0, 1, 1]
    // Accelerate curve for exits. easeEmphasized/easeSpring are decelerate
    // curves tuned for arrival — reused on close they leave the panel
    // lingering at low opacity until the hard unmap cuts it off, which is the
    // "jerky hide" this fixes. This one starts slow and finishes fast, so the
    // panel is genuinely gone by the time the window is dropped.
    readonly property var easeExit: [0.4, 0.0, 1.0, 1.0, 1, 1]

    // ── Motion vocabulary ──
    // How far a panel or row travels on the way in. Kept here rather than
    // spelled out per file so a cascade in the control centre and one in a
    // menu have visibly the same hand.
    readonly property real revealScale: 0.90
    readonly property real revealSlide: 18

    // stagger() used to live here and is now Direction.stagger(). The contract
    // says this file holds no timing policy beyond animation parameters, and a
    // cascade is not a parameter -- it is an order of events, which is the one
    // thing Direction exists to own. It was also the only number in the shell
    // that stayed fixed while the motion scale moved underneath it.
}
