pragma Singleton
import QtQuick

// Colors come from GeneratedColors (wallust-derived from the current
// wallpaper, regenerated by set-wallpaper.sh) instead of a fixed palette —
// that's what makes the whole DE (bar, panels, fuzzel) recolor itself
// automatically on wallpaper change instead of needing a manual retheme.
QtObject {
    readonly property color crust: Qt.darker(GeneratedColors.background, 1.15)
    readonly property color mantle: GeneratedColors.background
    readonly property color base: Qt.lighter(GeneratedColors.background, 1.12)

    readonly property color text: GeneratedColors.foreground
    readonly property color subtext1: GeneratedColors.subtext1
    readonly property color subtext0: GeneratedColors.subtext0

    readonly property color surface0: GeneratedColors.surface0
    readonly property color surface1: GeneratedColors.surface1
    readonly property color surface2: GeneratedColors.surface2

    readonly property color mauve: GeneratedColors.accent
    readonly property color blue: GeneratedColors.blue
    readonly property color red: GeneratedColors.red
    readonly property color green: GeneratedColors.green
    readonly property color yellow: GeneratedColors.yellow

    readonly property color accent: mauve

    // ── Drawing straight onto the wallpaper ──
    // Panels sit on their own frosted glass and can use `text` safely. The
    // desktop widgets have nothing behind them but the picture, and the accent
    // is derived from that same picture -- so on a bright wallpaper they were
    // being drawn light on light and all but disappeared.
    // Only for a still picture. A video's brightness is measured from one
    // extracted frame, which said 0.31 while the frame actually on screen was
    // 0.82 -- so for video the light treatment is not claimed and the halo
    // below does the work instead.
    readonly property bool wallpaperIsLight:
        !Wallpaper.isVideo && GeneratedColors.meanL > 0.55

    // What to draw on the bare desktop with, in two coherent modes.
    //
    // Light ink with a scrim under it is the default and the only thing that
    // works for video, whose brightness the estimate cannot know. Dark ink with
    // no scrim is used when a still picture is measurably bright, where dark on
    // light is better than either.
    //
    // The dark values are absolute rather than derived: darkening a background
    // that is already near-white gives light grey, which was the first attempt
    // and was unreadable on the white it was meant to fix.
    readonly property color deskInk: wallpaperIsLight
        ? Qt.hsla(0, 0, 0.13, 1)
        : GeneratedColors.foreground
    readonly property color deskAccent: wallpaperIsLight
        ? Qt.hsla(GeneratedColors.accent.hslHue, 0.55, 0.30, 1)
        : GeneratedColors.accent
    // The same alpha does not read the same in the two modes. Measured off the
    // gauge ring: 22% ink gives 1.90:1 against a dark wallpaper and only 1.57:1
    // against a white one, because the ground it sits on is what changed. 30%
    // brings the light mode back to the contrast the dark mode already had --
    // and it is 30 rather than 27 because the dark ink is #212121, not black,
    // so a given alpha lands lighter than the arithmetic on black suggests.
    readonly property real deskInkFaint: wallpaperIsLight ? 0.30 : 0.22

    // Only under light ink. Darkening the ground under dark ink only muddies it.
    readonly property real deskScrim: wallpaperIsLight ? 0 : 0.45

    // ── Type ──
    // One scale, named by role rather than by size, so a label in the bar and a
    // label in the control centre are the same thing by construction instead of
    // by two people picking 10 on separate days. Every size in the shell used to
    // be a literal: 12 and 11 appeared 78 times between them, 9/13/14/15/17/19
    // once or twice each, which is what a scale looks like when there isn't one.
    //
    // Inter is the interface face and Inter Display the optical size cut for
    // anything large — Display's tighter spacing and smaller apertures are what
    // stop a 132px clock reading as a blown-up body font. JetBrains Mono is kept
    // for genuinely tabular material.
    readonly property string fontFamily: "Inter"
    readonly property string fontDisplayFamily: "Inter Display"
    readonly property string fontMonoFamily: "JetBrains Mono"
    readonly property string fontIconFamily: "Symbols Nerd Font"

    readonly property int fontMicro: 9
    readonly property int fontLabel: 10
    readonly property int fontSmall: 11
    readonly property int fontBody: 12
    readonly property int fontLead: 13
    readonly property int fontTitle: 15
    readonly property int fontDisplay: 22
    readonly property int fontHero: 40

    // Tracking. Small type needs opening up and large type needs closing in;
    // both are what separates set type from defaulted type.
    readonly property real trackLabel: 1.2
    readonly property real trackBody: 0
    readonly property real trackDisplay: -0.6

    // ── Elevation ──
    // Three levels rather than one shadow reused everywhere: the bar sits on the
    // desktop, panels sit above the bar, and anything modal sits above those.
    // Reading the depth is how the eye knows which surface answers a click.
    // The base values mirror niri's own shadow block in 25-appearance.kdl, so
    // the shell's surfaces and real windows cast the same light.
    readonly property color shadowColor: "#11111b90"
    readonly property real shadowBlur: 40
    readonly property real shadowSpread: 4
    readonly property point shadowOffset: Qt.point(0, 6)

    readonly property real elevBarBlur: 22
    readonly property real elevBarSpread: 1
    readonly property real elevPanelBlur: 40
    readonly property real elevPanelSpread: 4
    readonly property real elevModalBlur: 72
    readonly property real elevModalSpread: 8

    // 10 matches niri's own geometry-corner-radius (40-window-rules.kdl) —
    // every quickshell panel uses the same radius as real windows so the
    // shell doesn't read as a separate layer bolted on top of the DE.
    readonly property int radius: 10
    // Popup panels round much harder than niri's own windows — at window
    // radius they read as plain dialogs rather than part of the shell.
    readonly property int radiusLarge: 24
    readonly property int spacing: 8
    // Islands need more presence than a hairline strip — at 28 the frosted
    // glass and its glow had no room to read as an actual surface.
    readonly property int barHeight: 34
    readonly property int barMargin: 8

    readonly property int animFast: 120
    readonly property int animNormal: 220
    readonly property int animSlow: 420
    // Panels leave faster than they arrive: a slow exit reads as sluggish,
    // and an accelerating curve reaches true 0 before the window unmaps so
    // there's no visible snap at the end (see easeExit).
    readonly property int animExit: 170

    // Material-3-style "emphasized" decelerate curve — everything that
    // settles into place (panel open, hover fill, list reveal) uses this
    // instead of a plain cubic so motion reads as designed rather than a
    // stock Qt tween. easeSpring adds a slight overshoot for elements that
    // should feel tactile (focused workspace pill, toast pop-in) — this is
    // the single biggest lever for the "caelestia-grade" cohesive-motion
    // look, since every animated Behavior in the shell pulls from the same
    // two curves instead of each panel inventing its own.
    readonly property var easeEmphasized: [0.05, 0.7, 0.1, 1.0, 1, 1]
    readonly property var easeSpring: [0.34, 1.70, 0.60, 1.0, 1, 1]
    // Harder overshoot for panel entrances — a small scale change reads as
    // barely animated, so opens punch in with this and a wider scale delta.
    // The overshoot is what carries "animated", not the duration: raising the
    // amplitude makes motion read as more deliberate, where raising the
    // duration would only make the shell feel slow to answer.
    readonly property var easeSpringBig: [0.22, 2.15, 0.45, 1.0, 1, 1]
    // Accelerate curve for exits. easeEmphasized/easeSpring are decelerate
    // curves tuned for arrival — reused on close they leave the panel
    // lingering at low opacity until the hard unmap cuts it off, which is the
    // "jerky hide" this fixes. This one starts slow and finishes fast, so the
    // panel is genuinely gone by the time the window is dropped.
    readonly property var easeExit: [0.4, 0.0, 1.0, 1.0, 1, 1]

    // ── Motion vocabulary ──
    // How far a panel or row travels on the way in. Kept here rather than
    // spelled out per file so a cascade in the control centre and one in a
    // menu have visibly the same hand.
    readonly property real revealScale: 0.90
    readonly property real revealSlide: 18

    // Per-item delay for a cascade. Capped: a fifty-node VPN list staggered
    // linearly would still be arriving a second and a half after it opened,
    // which reads as the shell being slow rather than as motion.
    function stagger(index) {
        return Math.min(Math.max(0, index), 9) * 34;
    }
}
