pragma Singleton
import QtQuick

// Colors come from GeneratedColors (wallust-derived from the current
// wallpaper, regenerated by set-wallpaper.sh) instead of a fixed palette —
// that's what makes the whole DE (bar, panels, fuzzel) recolor itself
// automatically on wallpaper change instead of needing a manual retheme.
QtObject {
    readonly property color crust: Qt.darker(GeneratedColors.background, 1.15)
    readonly property color mantle: GeneratedColors.background
    readonly property color base: Qt.lighter(GeneratedColors.background, 1.12)

    readonly property color text: GeneratedColors.foreground
    readonly property color subtext1: GeneratedColors.subtext1
    readonly property color subtext0: GeneratedColors.subtext0

    readonly property color surface0: GeneratedColors.surface0
    readonly property color surface1: GeneratedColors.surface1
    readonly property color surface2: GeneratedColors.surface2

    readonly property color mauve: GeneratedColors.accent
    readonly property color blue: GeneratedColors.blue
    readonly property color red: GeneratedColors.red
    readonly property color green: GeneratedColors.green
    readonly property color yellow: GeneratedColors.yellow

    readonly property color accent: mauve

    // 10 matches niri's own geometry-corner-radius (40-window-rules.kdl) —
    // every quickshell panel uses the same radius as real windows so the
    // shell doesn't read as a separate layer bolted on top of the DE.
    readonly property int radius: 10
    // Popup panels round much harder than niri's own windows — at window
    // radius they read as plain dialogs rather than part of the shell.
    readonly property int radiusLarge: 24
    readonly property int spacing: 8
    // Islands need more presence than a hairline strip — at 28 the frosted
    // glass and its glow had no room to read as an actual surface.
    readonly property int barHeight: 34
    readonly property int barMargin: 8

    // Mirrors niri's shadow block in 25-appearance.kdl exactly (color,
    // softness -> blur, spread, offset) for the same reason.
    readonly property color shadowColor: "#11111b90"
    readonly property real shadowBlur: 40
    readonly property real shadowSpread: 4
    readonly property point shadowOffset: Qt.point(0, 6)

    readonly property int animFast: 120
    readonly property int animNormal: 220
    readonly property int animSlow: 420
    // Panels leave faster than they arrive: a slow exit reads as sluggish,
    // and an accelerating curve reaches true 0 before the window unmaps so
    // there's no visible snap at the end (see easeExit).
    readonly property int animExit: 170

    // Material-3-style "emphasized" decelerate curve — everything that
    // settles into place (panel open, hover fill, list reveal) uses this
    // instead of a plain cubic so motion reads as designed rather than a
    // stock Qt tween. easeSpring adds a slight overshoot for elements that
    // should feel tactile (focused workspace pill, toast pop-in) — this is
    // the single biggest lever for the "caelestia-grade" cohesive-motion
    // look, since every animated Behavior in the shell pulls from the same
    // two curves instead of each panel inventing its own.
    readonly property var easeEmphasized: [0.05, 0.7, 0.1, 1.0, 1, 1]
    readonly property var easeSpring: [0.34, 1.70, 0.60, 1.0, 1, 1]
    // Harder overshoot for panel entrances — a small scale change reads as
    // barely animated, so opens punch in with this and a wider scale delta.
    // The overshoot is what carries "animated", not the duration: raising the
    // amplitude makes motion read as more deliberate, where raising the
    // duration would only make the shell feel slow to answer.
    readonly property var easeSpringBig: [0.22, 2.15, 0.45, 1.0, 1, 1]
    // Accelerate curve for exits. easeEmphasized/easeSpring are decelerate
    // curves tuned for arrival — reused on close they leave the panel
    // lingering at low opacity until the hard unmap cuts it off, which is the
    // "jerky hide" this fixes. This one starts slow and finishes fast, so the
    // panel is genuinely gone by the time the window is dropped.
    readonly property var easeExit: [0.4, 0.0, 1.0, 1.0, 1, 1]

    // ── Motion vocabulary ──
    // How far a panel or row travels on the way in. Kept here rather than
    // spelled out per file so a cascade in the control centre and one in a
    // menu have visibly the same hand.
    readonly property real revealScale: 0.90
    readonly property real revealSlide: 18

    // Per-item delay for a cascade. Capped: a fifty-node VPN list staggered
    // linearly would still be arriving a second and a half after it opened,
    // which reads as the shell being slow rather than as motion.
    function stagger(index) {
        return Math.min(Math.max(0, index), 9) * 34;
    }
}
