[config]
reload_apps = false

[templates.quickshell]
input_path = "templates/yoake_matugen_colors.json.template"
output_path = "~/.local/state/yoake/qs_colors.json"

[templates.fastfetch]
input_path = "templates/fastfetch.jsonc.template"
output_path = "~/.config/fastfetch/config.jsonc"

[templates.kitty]
input_path = "templates/kitty-colors.conf.template"
output_path = "~/.config/kitty/colors.conf"

[templates.cava]
input_path = "templates/cava-colors.ini.template"
output_path = "~/.config/cava/config"
