[config]
reload_apps = false

[templates.kitty]
input_path = "templates/kitty-colors.conf.template"
output_path = "~/.config/kitty/colors.conf"

[templates.cava]
input_path = "templates/cava-colors.ini.template"
output_path = "~/.config/cava/config"

[templates.fastfetch]
input_path = "templates/fastfetch.jsonc.template"
output_path = "~/.config/fastfetch/config.jsonc"
